require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IngredientsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Ingredient. As you add validations to Ingredient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'MyString', description: 'MyText' }
  end

  let(:invalid_attributes) do
    { name: '', description: '' }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngredientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :all do
    User.destroy_all
    Role.destroy_all

    @admin_role = Role.create! name: 'admin'
    @cook_role = Role.create! name: 'cook'

    @admin = create_sample_user 'admin', @admin_role
    @cook = create_sample_user 'cook', @cook_role
  end

  before :each do
    Ingredient.destroy_all

    ["Alcaparra", "Pimenta", "Cominho", "Alho"].each do |name|
      Ingredient.create! name: name, description: name
    end
  end

  describe 'GET #index' do
    it 'searchs for ingredients' do
      get :index, :search=>"alh", session: valid_session
      expect(assigns(:ingredients).size).to eq(1)
    end

    it 'sort ingredients by name by default' do
      ingredients = ["Alcaparra", "Pimenta"]
      get :index, :search=>nil, session: valid_session

      expect(assigns(:ingredients).first.name).to eq(ingredients.first)
      expect(assigns(:ingredients).last.name).to eq(ingredients.last)
    end
  end

  describe 'GET #show' do
    it 'assigns the requested ingredient as @ingredient' do
      ingredient = Ingredient.create! valid_attributes
      get :show, id: ingredient.to_param , session: valid_session
      expect(assigns(:ingredient)).to eq(ingredient)
    end
  end

  describe 'GET #new' do
    it 'assigns a new ingredient as @ingredient' do
      sign_in @cook
      get :new, session: valid_session
      expect(assigns(:ingredient)).to be_a_new(Ingredient)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested ingredient as @ingredient' do
      # Only admin can edit
      sign_in @admin
      ingredient = Ingredient.create! valid_attributes
      get :edit, id: ingredient.to_param, session: valid_session
      expect(assigns(:ingredient)).to eq(ingredient)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Ingredient' do
        sign_in @cook

        expect do
          post :create,
               ingredient: valid_attributes,
               session: valid_session
        end.to change(Ingredient, :count).by(1)
      end

      it 'assigns a newly created ingredient as @ingredient' do
        sign_in @cook

        post :create,
             ingredient: valid_attributes,
             session: valid_session
        expect(assigns(:ingredient)).to be_a(Ingredient)
        expect(assigns(:ingredient)).to be_persisted
      end

      it 'redirects to the created ingredient' do
        sign_in @cook

        post :create,
             ingredient: valid_attributes,
             session: valid_session
        expect(response).to redirect_to(Ingredient.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved ingredient as @ingredient' do
        sign_in @cook

        post :create,
             ingredient: invalid_attributes,
             session: valid_session
        expect(assigns(:ingredient)).to be_a_new(Ingredient)
      end

      it 're-renders the \'new\' template' do
        sign_in @cook

        post :create,
             ingredient: invalid_attributes,
             session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        { name: 'updated', description: 'updated' }
      end

      it 'updates the requested ingredient' do
        sign_in @admin # only admin can edit

        ingredient = Ingredient.create! valid_attributes

        put :update,
            id: ingredient.to_param,
            ingredient: new_attributes,
            session: valid_session
        ingredient.reload

        expect(ingredient.name).not_to eq(valid_attributes[:name])
      end

      it 'assigns the requested ingredient as @ingredient' do
        sign_in @admin
        ingredient = Ingredient.create! valid_attributes
        put :update,
            id: ingredient.to_param,
            ingredient: valid_attributes,
            session: valid_session
        expect(assigns(:ingredient)).to eq(ingredient)
      end

      it 'redirects to the ingredient' do
        sign_in @admin
        ingredient = Ingredient.create! valid_attributes
        put :update,
            id: ingredient.to_param,
            ingredient: valid_attributes,
            session: valid_session
        expect(response).to redirect_to(ingredient)
      end
    end

    context 'with invalid params' do
      it 'assigns the ingredient as @ingredient' do
        sign_in @admin
        ingredient = Ingredient.create! valid_attributes
        put :update,
            id: ingredient.to_param,
            ingredient: invalid_attributes,
            session: valid_session
        expect(assigns(:ingredient)).to eq(ingredient)
      end

      it 're-renders the \'edit\' template' do
        sign_in @admin
        ingredient = Ingredient.create! valid_attributes
        put :update,
            id: ingredient.to_param,
            ingredient: invalid_attributes,
            session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested ingredient' do
      sign_in @admin
      ingredient = Ingredient.create! valid_attributes
      expect do
        delete :destroy,
               id: ingredient.to_param,
               session: valid_session
      end.to change(Ingredient, :count).by(-1)
    end

    it 'redirects to the ingredients list' do
      sign_in @admin
      ingredient = Ingredient.create! valid_attributes
      delete :destroy,
             id: ingredient.to_param,
             session: valid_session
      expect(response).to redirect_to(ingredients_url)
    end
  end

  private

    def create_sample_user name, role
      user = User.create! first_name: "test#{name}",
                          last_name: "test#{name}",
                          email: "#{name}@user.com",
                          password: "test#{name}",
                          username: "test#{name}",
                          role: role
      user
    end
end
